### PR TITLE
Header link update and capitalization

### PR DESCRIPTION
**Pull request by emiluzelac**
Itty-bitty update for header comment block and new functions link.

### CODE REVIEW

**Comment by emiluzelac** [comment]
Also changed `Set up` to `Setup`, it reads much better and to reflect https://github.com/WordPress/WordPress/blob/master/wp-content/themes/twentyfifteen/functions.php#L109

**Comment by obenland** [comment]
Setup is one word when it is a noun (e.g., “it was a setup!”) or an adjective (e.g., “follow the setup instructions”). It is two words—set up—when it functions as a verb (e.g., “I'm going to set up the computer”).

I also don't think we need to capitalize the word `functions` here.

Maybe we should do a documentation link sweep at some point and update them all to point to handbook pages instead of doing this one by one.

**Comment by emiluzelac** [comment]
Updated. Should we also change https://github.com/WordPress/WordPress/blob/master/wp-content/themes/twentyfifteen/functions.php#L109 too?

All right, no more link updates. We can wait till everything is done, sorry!

**Comment by emiluzelac** [comment]
Thanks!

**Pull request merged**
