### PR TITLE
Clean up trailing whitespace

### PR DESCRIPTION
**Pull request by josephfusco**

### CODE REVIEW

**Comment by philiparthurmoore** [comment]
This looks fine but can you please show me a pre and post fix screenshot from your code editor? It's super-hard to rely 100% on GitHub for whitespace-related diffs.

**Comment by karmatosed** [comment]
@philiparthurmoore you can test it yourself without asking for screenshots. Ideally that's better to save time.

**Comment by philiparthurmoore** [comment]
Not really. It helps me test why someone may be seeing something different than I do or GitHub does.

**Comment by josephfusco** [comment]
**NOTE:** I personally use this handy Atom package https://atom.io/packages/trailing-spaces in addition to showing invisible characters within the editor. You can see the package highlighting the whitespace below:

screen shot 2016-07-14 at 8 33 03 am

**Comment by philiparthurmoore** [comment]
I generally rely on Sublime's whitespace visibility which is fantastic. The only reason I ask for screenshots in PRs is because it helps put stuff in context and makes a much stronger case for merging. Either way it's a good PR.

I think @obenland might have shown me whitespace visibility a long long time ago in Tokyo (glorious days)? Can't remember. It's disappointing that different editors and GitHub don't always look the same. It makes simple requests like this way too time consuming to resolve.

**Pull request merged**
