### PR TITLE
Removed widget search submit styles.

### PR DESCRIPTION
**Pull request by iamdmitrymayorov**
Another way of resolving #849. Completely remove search widget styles.

### CODE REVIEW

**Comment by karmatosed** [comment]
Can you refresh or remove this PR?

**Comment by iamdmitrymayorov** [comment]
@karmatosed Done and done! It should all be fine now.

**Comment by jrfnl** [comment]
@iamdmitrymayorov Oops.. looks like there are git artefacts in the commit..

**Comment by iamdmitrymayorov** [comment]
@jrfnl oh boy, I'll fix it right away.

**Pull request merged**
