### PR TITLE
Improved _s_categorized_blog() function

### PR DESCRIPTION
**Pull request by gregrickaby**
- Remove `hide_empty` (the default is 1). https://codex.wordpress.org/Function_Reference/get_categories
- Add more inline comments to help teach folks about using transients.
- Use Yoda conditional to check $all_the_cool_cats to better fit WordPress PHP standards.(https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#yoda-conditions)
- Remove if/else statement. Instead return `false` earlier.

### CODE REVIEW

**Comment by davidakennedy** [comment]
@gregrickaby Thanks for the updated PR! The build failed because you need a period after this comment on line 87. :smile: 

> // Check for transient, if none, go count the categories

Want to fix and squash the commits?

@obenland I think you had some feedback on the previous PR. Want to take a look at this one?

**Comment by gregrickaby** [comment]
@davidakennedy All set.

**Comment by gregrickaby** [comment]
@davidakennedy I'm not going to lie. I have no idea how to squash commits and probably screwed this damn PR up all over again...

**Comment by obenland** [comment]
Commits are not squashed.

**Comment by gregrickaby** [comment]
Neither myself nor Ben Lobaugh can get this PR squashed for some reason. I'm blowing up this PR too. :rage:

**Pull request closed without merging**
