### PR TITLE
Declare enhanced WooCommerce theme support

### PR DESCRIPTION
**Pull request by nielslange**
#### Changes proposed in this Pull Request:

Added WooCommerce theme support as described in [Declaring WooCommerce support in themes](https://github.com/woocommerce/woocommerce/wiki/Declaring-WooCommerce-support-in-themes).

#### Related issue(s):

#1278

### CODE REVIEW

**Comment by tiagonoronha** [comment]
@nielslange thanks for the pull request! :)

One of the functions you removed, `_s_woocommerce_products_per_page()`, is used on a different function: https://github.com/nielslange/_s/blob/973876d14d62c8bfd16194a6ff0b7cc3228e1798/inc/woocommerce.php#L119

If you visit the Shop page with the changes in your pull request you'll get a Fatal Error:

`Fatal error: Uncaught Error: Call to undefined function _s_woocommerce_loop_columns() in /app/public/wp-content/themes/_s/inc/woocommerce.php`

You've a few options:

1) Add that function back, and do something like this: https://github.com/woocommerce/storefront/blob/master/inc/woocommerce/storefront-woocommerce-template-functions.php#L180-L196

2) Replace that function call with `wc_get_default_products_per_row()` instead.

3) Remove the wrappers completely from `_s`, as I'm doing in Storefront on this pull request: https://github.com/woocommerce/storefront/pull/779/files

As of WooCommerce 3.3, the column wrappers as not needed anymore because WooCommerce will add the number of columns to the wrapping div.

I suggest you go with option 3 and remove the wrapper completely, as that is the most future proof solution, but you might need to adjust the CSS if products are not displayed on a grid afterwards.

**Comment by grappler** [comment]
@nielslange Is this something you still want to work on?

**Comment by nielslange** [comment]
> @nielslange Is this something you still want to work on?

Sure, @grappler! I'm currently travelling and have limited time, but I'm happy to pick up this issue and finalise it.

**Comment by nielslange** [comment]
Closed in favour of #1330

**Pull request closed without merging**
