### PR TITLE
Update Normalize to 7.0.0

### PR DESCRIPTION
**Pull request by B-07**
#### Changes proposed in this Pull Request:
_normalize.scss and style.css

#### Related issue(s): there's a PR #1155 but it's not complete, here's the full changes required

### CODE REVIEW

**Comment by tyrann0us** [comment]
Duplicate of #1155?

**Comment by B-07** [comment]
I don't know what you mean by duplicate

**Comment by jrfnl** [comment]
@B-07 *duplicate* means that you are sending in a PR for something where there is already a PR open for the same.

On a completely different note: PLEASE *describe* **what** you are changing and **why** in your PR description.
Listing the files changed is useless as that's what the "Files changed" tab is all about.

**Comment by B-07** [comment]
As I mentioned, there's a PR which has partial changes that are required, I did the additional changes and created a new PR as I cannot modify others PR

**Comment by m-e-h** [comment]
I think there is still discussion going on about how best to include normalize. https://github.com/Automattic/_s/issues/1144

**Comment by davidakennedy** [comment]
Thanks for the pull request, @B-07! I'm going to close this in favor of #1155. It's cool to have you jump in and contribute, but let's give @mtomas7 a chance to see his PR through. 😄 

If he doesn't have time, we can always reopen this one.

**Pull request closed without merging**
