### PR TITLE
Remove link around header image

### PR DESCRIPTION
**Pull request by samikeijonen**
Fixes issue #1041.

### CODE REVIEW

**Comment by samikeijonen** [comment]
I switched to `the_header_image_tag()` function. It handles the responsive image markup by default.

**Comment by grappler** [comment]
Really good change. Should be merged.

**Comment by jrfnl** [comment]
I can't find any information on the minimum WP version `_s` is supposed to support at the moment (anyone?). As the `the_header_image_tag()` was introduced in WP 4.4, should the example code be surrounded by a `function_exists()` check ?

**Comment by grappler** [comment]
`_s` supports the last 3 versions. That the what the TRT recommends and the `_s` follows. It should be fine if we wait till `4.7` is released.

**Comment by jrfnl** [comment]
@grappler I just can't find any mention of that in the readme or anywhere else...

**Comment by grappler** [comment]
@jrfnl You can find it mentioned in a few older PRs https://github.com/Automattic/_s/pull/644 The guideline is mentioned https://make.wordpress.org/themes/handbook/review/required/

**Pull request merged**
