### PR TITLE
Adding a Pull Request Template

### PR DESCRIPTION
**Pull request by laurelfulford**
I'd like to propose adding a simple Pull Request template, so information is requested when you make a PR.

It can be easy to miss this step or specific details when creating a PR; having some kind of prompt could be a good reminder.

### CODE REVIEW

**Comment by grappler** [comment]
It seems like a good idea. I wondering if there any other examples that would could look at to compare the text to.

We should not forgot to add the file as an excluded file to underscores.me https://github.com/Automattic/underscores.me/blob/master/plugins/underscoresme-generator/underscoresme-generator.php#L122

**Comment by davidakennedy** [comment]
I really think it's time for this. 😄 

Good call @grappler, I can take care of those file additions after merge.

I also think it might be a good idea to add a simple [issue template as well](https://help.github.com/articles/creating-an-issue-template-for-your-repository/).

Calypso uses this for an issue template. It's overkill for our needs here, but I like how it encourages thoroughness:

```<!-- Thanks for contributing to Calypso! Pick a clear title ("Editor: add spell check") and proceed. -->

#### Steps to reproduce
1. Starting at URL:
2.
3.
4.

#### What I expected


#### What happened instead


#### Browser / OS version


#### Screenshot / Video


#### Context / Source
<!-- Optional: share your unique context to help us understand your perspective. You can add context tags such as: #journey #anecdote #narrative #context #empathy #perspective #reallife #dogfooding #livesharing #flowsharing #anxiety #anxiety-flow #stresscase #painpoint.

We'd also love to know how you found the bug: #dogfooding, #manual-testing, #automated-testing, or #user-report if applicable.

If requesting a new feature, explain why you'd like to see it added.
-->



<!--
PLEASE NOTE
- These comments won't show up when you submit the issue.
- Everything is optional, but try to add as many details as possible.

Docs & troubleshooting:
https://github.com/Automattic/wp-calypso/blob/master/.github/CONTRIBUTING.md
https://github.com/Automattic/wp-calypso/blob/master/docs/troubleshooting.md

Helpful tips for screenshots:
https://en.support.wordpress.com/make-a-screenshot/
-->```

**Comment by laurelfulford** [comment]
Thanks all!

Added a PR for the underscores.me website to ignore the .github directory, where the PR template lives: https://github.com/Automattic/underscores.me/pull/58

**Comment by alaczek** [comment]
LGTM!

**Pull request merged**
