### PR TITLE
compress screenshot for 92% savings! bradp@067dac2

### PR DESCRIPTION
**Pull request by mrwweb**
I should've done this originally in 4da6d65, but better late than never!

### CODE REVIEW

**Comment by obenland** [comment]
Actually, would you mind increasing the image size to 1200x900? The WPTRT increased the allowed size recently and we could set a good example here.

**Comment by philiparthurmoore** [comment]
@obenland When was that requirement changed? Got a link? On my phone so a bit difficult to find.

**Comment by obenland** [comment]
I proposed the change a few weeks back to make screenshots in the new Directory retina compatible. The handbook was only updated today: https://make.wordpress.org/themes/handbook/review/required/#screenshot

**Comment by philiparthurmoore** [comment]
Awesome. Thanks for that information.

**Comment by mrwweb** [comment]
Great. I had no idea. Will update shortly.

**Comment by mrwweb** [comment]
Okey dokey! Bigger image and—somehow—an even smaller file size.

**Pull request closed without merging**
