### PR TITLE
Add woocommerce to docs

### PR DESCRIPTION
**Pull request by bahiirwa**
#### Changes proposed in this Pull Request:
Add information to documentation that _s is Woocommerce ready with a starter boilerplate

#### Related issue(s):

### CODE REVIEW

**Comment by grappler** [comment]
Thank you @bahiirwa for the pull request. It is a good idea to mention the WooComerce support.

All of the other points are a sentence. It would make sense to make this point a full sentence too. It would be good to mention what type of WooComerce support is included.

**Comment by bahiirwa** [comment]
Thanks for the directions @grappler , I hope that is more inclusive.

**Comment by crunnells** [comment]
Hey @bahiirwa it looks like a couple of other commits were pushed to this PR that aren't related to adding WooCommerce. Can you revert the last two commits (e020eb6 and 134f282) and then we can merge this.

**Comment by bahiirwa** [comment]
Sorry, my git is not that great. I shall close this and submit again.

**Pull request closed without merging**
