### PR TITLE
Remove removed PHPCS rule

### PR DESCRIPTION
**Pull request by szepeviktor**
to fix CI

was https://travis-ci.org/Automattic/_s/jobs/492470379#L600

### CODE REVIEW

**Comment by szepeviktor** [comment]
much better: https://travis-ci.org/Automattic/_s/jobs/586252288#L620-L663
now there are only small style errors

**Comment by szepeviktor** [comment]
@crunnells Automattic decided to halt _s developement?

**Comment by jrfnl** [comment]
@szepeviktor Please see #1311

Regarding the specific sniff: the sniff has not been removed, but has been renamed. Though instead of updating the name in the ruleset, it would be better to switch to `PHPCompatibilityWP` instead (which is what is done in #1311, though that PR is very out of date and I have little motivation to update it as PRs in this repo are being left to rot instead of being merged).

**Comment by Ismail-elkorchi** [comment]
@szepeviktor Thank you for the PR and for your willingness to contribute to this project. As Juliette said, the changes regarding this sniff must be done in https://github.com/Automattic/_s/pull/1311. So I'm going to close this PR.

@jrfnl If you have the time, the motivation and the energy to update https://github.com/Automattic/_s/pull/1311, I'd be willing to review it and then merge it promptly.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by jrfnl** [comment]
@Ismail-elkorchi Working on WPCS 3.0 for the moment, let's update that PR after the that's done so it is ready for the future.

**Comment by Ismail-elkorchi** [comment]
@jrfnl That's really awesome. Thank you for your great work.

**Pull request closed without merging**
