### PR TITLE
Correct code indentation

### PR DESCRIPTION
**Pull request by truongwp**
The code inside if block should be indented. The current indentation makes PHPCS errors.

### CODE REVIEW

**Comment by grappler** [comment]
Thank you for the pull request. I am surprised that there is a PHPCS error for this code as there have been no errors in travis.

This is not the only place where this type of indentation is used for pluggable functions. If we were to change it we would need to do it every where.

We are currently discussion removing the `functions_exists()` for this function https://github.com/Automattic/_s/issues/1116

I don't think the extra indentation make sense to add here.

**Comment by jrfnl** [comment]
> I am surprised that there is a PHPCS error for this code as there have been no errors in travis.

That particular sniff is explicitly excluded for `_s` and I'd personally recommend excluding it for themes anyhow as for files combining PHP and HTML I've found that sniff to be quite buggy.

@truongwp You may be interested to have a look at the custom PHPCS ruleset which is included with `_s` which is a good example for a ruleset to be used for WP themes.
https://github.com/Automattic/_s/blob/master/phpcs.xml.dist

**Comment by truongwp** [comment]
Sorry because I used my PHPCS rule set. But I think it still violates WordPress coding standard.
Remove checking function exists is a good idea because we can use `remove_action()`

**Comment by grappler** [comment]
We we were to take the indention to the letter then we should remove the exceptions in the `phpcs.dist.xml` and make sure the indention is fix every where.

```
<exclude name="Generic.WhiteSpace.ScopeIndent.IncorrectExact" />
<exclude name="Generic.WhiteSpace.ScopeIndent.Incorrect" />
<exclude name="PEAR.Functions.FunctionCallSignature.Indent" />
```

**Comment by jrfnl** [comment]
> We we were to take the indention to the letter then we should remove the exceptions in the phpcs.dist.xml and make sure the indention is fix every where.

I'd definitely wait until WPCS 0.12.0 in that case as we're working on adding some extra sniffs which should make some of the indent sniffs which are excluded slightly less buggy - at least for the fixer part -. Some sniffs work better when used together with others.
For more information, check out https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1000

**Comment by grappler** [comment]
@truongwp As WPCS 0.12.0 has been released could you have a look how the correct code indentation would look like on all of the files and not just `functions.php`?

**Comment by truongwp** [comment]
Hi @grappler,
I have just corrected all indentation errors when check function_exists in all files.
And when I runned phpcs, I saw that there are some other phpcs errors like: `Newline required after opening brace` or `Closing PHP tag must be on a line by itself`. Should I create a new PR to fix them?

**Comment by grappler** [comment]
@truongwp No that is fine. I have a PR open for those issues. #1157

**Comment by grappler** [comment]
Thanks this looks good. With the introduction of these changes we can remove
```xml
<exclude name="Generic.WhiteSpace.ScopeIndent.Incorrect" />
<exclude name="PEAR.Functions.FunctionCallSignature.Indent" />
```

To be able to remove the following exception there needs to be two fixes in `inc/custom-header.php` and `comments.php`.
`<exclude name="Generic.WhiteSpace.ScopeIndent.IncorrectExact" />`
Could you make the remaining two changes to `inc/custom-header.php` and `comments.php`?

The remaining line indent issue in `header.php` will be fixed by the changes in #1157.

**Comment by truongwp** [comment]
@grappler I added the commit.

**Comment by grappler** [comment]
Thanks @truongwp! I have tested this and it works great. Could you squash the commits together? Will then approve it.

**Comment by truongwp** [comment]
@grappler Yes, I squashed the commits to one.

**Comment by davidakennedy** [comment]
Hi @truongwp – this looks solid. Thanks for the pull request! I see one issue. It looks like support for `custom-logo` was removed, probably unintentional. 😄  Could you add that back in, and squash your commits.

**Comment by truongwp** [comment]
@davidakennedy Sorry about the mistake. I restored custom-logo.

**Comment by davidakennedy** [comment]
Thank you @truongwp!

**Pull request merged**
