### PR TITLE
Remove default implicit ARIA semantics

### LINKED ISSUE #889: Remove default implicit ARIA semantics
>  Web developers should not set the ARIA role and aria-* attributes to values that match the default implicit ARIA semantics defined in the table.

Quoted from the [W3C working draft about ARIA in HTML](http://www.w3.org/TR/html-aria/#document-conformance-requirements-for-use-of-aria-attributes-in-html).

The default implicit ARIA semantics should not be used in the markup.

PR #890

### PR DESCRIPTION
**Pull request by benoitchantre**
The default implicit ARIA semantics should not be used in the markup.

Fixes #889

### CODE REVIEW

**Comment by emiluzelac** [comment]
Yep, I was looking at that myself as well.

screen shot on 2015-12-20 at 13-55-48

**Comment by samikeijonen** [comment]
Here is related issue #786.

**Comment by emiluzelac** [comment]
Makes sense, thanks!

**Comment by sixhours** [comment]
Closing as per discussion in #889

**Pull request closed without merging**
