### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by B-07**
line no 11, it says `_s` -based theme. I think the `-` before `based` is not necessary there

### CODE REVIEW

**Comment by grappler** [comment]
Does the search and replace on underscores.me still work with this change? In this case the `_s` should not be replaced by the new theme name.

**Comment by B-07** [comment]
Not sure what you mean.

**Comment by grappler** [comment]
When generating a theme on underscores.me the scripts looks for specific cases of `_s` to replace with the theme name that you have defined in the form. Maybe the dash was a way to prevent this instance of `_s` to be replaced as if it was replaced the sentence would not make sense.

**Comment by B-07** [comment]
This is in CONTRIBUTING.md file, so I guess this won't replaced by any script while generating a new theme :)

**Pull request merged**
