### PR TITLE
DRY gallery columns

### PR DESCRIPTION
**Pull request by josephfusco**
see: http://www.sassmeister.com/gist/454a46889fca4d8e4b3384198e987e99

### CODE REVIEW

**Comment by philiparthurmoore** [comment]
This in theory looks pretty legit but could someone with more Sass chops weigh in?

**Comment by slushman** [comment]
+1. I have this is my branch of _s with the intention of contributing the same thing here. Joseph beat me to it. :)

**Comment by karmatosed** [comment]
I'm actually -1 for this because of legibility - this in theory could be ok but when we created our Sass we tried to not have overly complex code on purpose.

**Comment by tyrann0us** [comment]
Just for reference: SASSified gallery styles based on Twenty Seventeen: https://gist.github.com/tyrann0us/b58ac4477a5b30d123df35ca27d878bd

**Comment by josephfusco** [comment]
Can we get a few more people to weigh in on this?

I would consider this utilizing a standard Sass features rather than being overly complex. This is a fairly common Sass pattern to loop through repetitive elements & properties.

If this project is only using Sass for variables & breaking up different sections into partials and nothing more, we should add that somewhere.

**Comment by gatespace** [comment]
+1 for adding explanatory comments.

**Comment by bahiirwa** [comment]
+1 for the code refactor. Good use of the basic for loop. Comments are welcome

**Comment by joshmcrty** [comment]
+1 for the loop and for adding explanatory comments to help new sass users who come across this

**Comment by josephfusco** [comment]
Comment added! @davidakennedy can we merge this in? :)

**Comment by davidakennedy** [comment]
Thanks @josephfusco for the ping and updated PR.

Overall, I'm okay with this. It's basic enough with the comment, and a good use of Sass.

Pinging other maintainers, @laurelfulford and @allancole, for some second opinions.

**Comment by allancole** [comment]
Yeah, I think this looks good @davidakennedy & @josephfusco

**Comment by laurelfulford** [comment]
I think it looks good, too! 

Should the style.css be updated as well, to match the exact percentages? The updated version includes a bit less rounding:

.gallery-columns-3's max-width was 33.33% and is now 33.33333%

.gallery-columns-6 max-width was 16.66% and is now 16.66667%

.gallery-columns-7 max-width was 14.28% and is now 14.28571%

.gallery-columns-9 max-width was 11.11% and is now 11.11111%

**Pull request merged**
