### PR TITLE
Add -moz-appearance as well

### PR DESCRIPTION
**Pull request by mkrdip**
```
-webkit-appearance: value; /* Chrome & Safari */
-moz-appearance: value; /* Firefox */
```

### CODE REVIEW

**Comment by sarahmonster** [comment]
I'm not certain about this, but this is likely because I've never found much occasion to use `-moz-appearance`, because Firefox tends to render input elements in expected ways. 

What does adding this property achieve here?

**Comment by corvannoorloos** [comment]
Even though it's a valid point, my preference would be to leave [normalize.css](https://github.com/necolas/normalize.css) as is.

**Comment by philiparthurmoore** [comment]
Probably best to maintain parity with normalize here.

**Comment by karmatosed** [comment]
I'd say lets leave normalize as it is for now. It's very much a personal choice to use this. You are as with anything _s related welcome to fork and create your own version. That's the joy of _s.

**Pull request closed without merging**
