### PR TITLE
calculate gallery image size

### PR DESCRIPTION
**Pull request by marcobiedermann**
Calculate gallery image size instead of hardcoding the values is more maintainable and understandable.

Btw. which tool do you use to compile the Scss files?

### CODE REVIEW

**Comment by sixhours** [comment]
This works for me in testing! Good idea.

I'm not sure why we're dividing 100% by 1 in the parent `width` attribute; would there ever be a situation where we'd want to calculate a different value there? Doesn't hurt anything, but seems unnecessary.

We also need to compile the Sass and update style.css to match before we merge this.

**Comment by marcobiedermann** [comment]
@sixhours 
> I'm not sure why we're dividing 100% by 1 in the parent width attribute;

You are absolutely right, dividing by 1 is irrelevant to the calculation but I used to intentionally to create a pattern, which is a bit easier to follow (dividing by 1, 2, 3, 4 …).

> We also need to compile the Sass and update style.css to match before we merge this.

Yes sure, but I do not know which compiler is used for this project.

**Comment by sixhours** [comment]
> Yes sure, but I do not know which compiler is used for this project.

Good question....I think we've been updating style.css manually for changes like this, but someone else may be able to confirm.

**Comment by philiparthurmoore** [comment]
Let's close this and do it the #986 way. Sound good?

**Comment by marcobiedermann** [comment]
@philiparthurmoore I agree!

**Pull request closed without merging**
