### PR TITLE
WPCS: Update the custom PHPCS ruleset for the release of WPCS 0.12.0

### PR DESCRIPTION
**Pull request by jrfnl**
* Verify that everything in the global namespace is prefixed with a theme prefix.
* Verify that no deprecated or removed WP classes are being used.
* Verify that no deprecated or removed WP function parameters are being used.

The build for this PR will not pass until a number of issues are addressed. This is being handled in a separate PR #1157

### CODE REVIEW

**Comment by grappler** [comment]
I think we should leave out `WordPress.NamingConventions.PrefixAllGlobals` till we have fixed WordPress-Coding-Standards/WordPress-Coding-Standards#1043.

We can also remove `<exclude name="PEAR.Functions.FunctionCallSignature.Indent" />` as it does not prevent any errors anymore.

**Comment by jrfnl** [comment]
> I think we should leave out WordPress.NamingConventions.PrefixAllGlobals till we have fixed

What about adding it, but commenting it out with a "Temporarily disabled until..." comment ? That way it still serves as an example for others without breaking the build for now.

**Comment by grappler** [comment]
> What about adding it, but commenting it out with a "Temporarily disabled until..." comment ?

I am undecided. Part of the problem is fixed with excluding the check on `404.php`, `comments.php` and `header.php`. At the moment we do not have a way to whitelist `$content_width` and `$themecolors`.

FYI #1140 will fix the indentation errors. The PR can be updated once that is merged.

**Comment by jrfnl** [comment]
I've rebased the PR as #1140 has been merged, PR #1157 should solved the remaining issues.

**Pull request closed without merging**
