### PR TITLE
Change links from http to https

### PR DESCRIPTION
**Pull request by B-07**
Since both of the sites are secured with ssl

#### Changes proposed in this Pull Request:
style.css

#### Related issue(s):n/a

### CODE REVIEW

**Comment by gatespace** [comment]
It is best to modify the Sass file at the same time.

* https://github.com/Automattic/_s/blob/master/sass/style.scss#L3
https://github.com/Automattic/_s/blob/master/sass/style.scss#L5

**Comment by B-07** [comment]
Done!

**Comment by grappler** [comment]
There are a few more places where the urls can be changed to HTTPS. Could you do it for all of the files? In the end do you think you could squash all of the commits into one? This will help with a clean history in the future. This article explains how to do it. https://www.devroom.io/2011/07/05/git-squash-your-latests-commits-into-one/ You will need force push the changes to GitHub. You can do it with this command `git push --force`.

If you need help doing it you can ping me on wordpress.slack.com I am happy to help you.

**Comment by davidakennedy** [comment]
@B-07 Want to bring in the updates from #1177 here? Then squash your commits, and I'll merge. Thanks!

**Comment by grappler** [comment]
Closing as it is fixed in #1214

**Pull request closed without merging**
