### PR TITLE
updated the customizer selectors to match the custom-header.php line …

### PR DESCRIPTION
**Pull request by carl-alberto**
updated the customizer selectors to match the custom-header.php line as per advice from @davidakennedy

### CODE REVIEW

**Comment by davidakennedy** [comment]
Thanks for the update. Almost there! Can you:

Make line 25 match what you've changed. This:

```javascript
$( '.site-title a, .site-description' )
```

Should be:

```javascript
$( '.site-title, .site-description' )
```

So it matches the selector below on line 30. Make sense?

**Comment by carl-alberto** [comment]
Hi @davidakennedy 
Thanks for the directions, updated as per your recommendations :)

**Comment by davidakennedy** [comment]
@carl-alberto Looks perfect! We're ready to merge.

Would you mind squashing your commits into one? [See this article](https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit).

That way, we have a cleaner commit history.

Thanks for all your time and work on this issue! :+1:

**Comment by carl-alberto** [comment]
I hope I got the squashing method correctly, here is the pull request: https://github.com/Automattic/_s/pull/852

Thanks

**Comment by davidakennedy** [comment]
@carl-alberto Not quite. There are still four commits in that new PR. You should try to work off of the existing branch you've worked on. The idea here to put everything into one commit. This tutorial is a bit clearer than the other: https://davidwalsh.name/squash-commits-git

Can you give it another try? Thanks – I know it's kind of confusing so no worries.

I'm going to close the other PR.

I'm going to add some instructions about this to our contributor docs.

**Pull request closed without merging**
