### PR TITLE
Remove aria-haspopup

### PR DESCRIPTION
**Pull request by samikeijonen**
Fixes issue #1045.

### CODE REVIEW

**Comment by jrfnl** [comment]
Could you squash the commits /remove the first three irrelevant commits from the PR ?

**Comment by samikeijonen** [comment]
> Could you squash the commits /remove the first three irrelevant commits from the PR ?

Do you have any tutorial how to do that?

**Comment by MunifTanjim** [comment]
@samikeijonen Check this: [squashing commits with rebase](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)

**Comment by karmatosed** [comment]
If we can get just the patch for this rather than the other things that would be great.

**Comment by karmatosed** [comment]
Actually don't worry about squashing as we're merging the others so should be all good.

**Pull request merged**
