### PR TITLE
Updated Sass and CSS files to remove numbered TOC structure

### PR DESCRIPTION
**Pull request by hugobaeta**
This patch removed the numbers from the Table of Contents in the Sass and CSS files, so that theme authors can have more flexibility when using _s as a base.

Related to issue #709

### CODE REVIEW

**Comment by jacklenox** [comment]
:+1: I agree with this change.

**Comment by emiluzelac** [comment]
It's quick and dirty but definitely makes sense to me, we all rewrite them
anyway. 👍

**Comment by hugobaeta** [comment]
@karmatosed @obenland @ianstewart - can I get your input on this and eventually a pull if we all agree?

**Comment by obenland** [comment]
I think it's missing `/sass/navigation/_navigation.scss`

**Comment by hugobaeta** [comment]
@obenland I just committed that missing change to this branch. thanks for noticing!

**Comment by obenland** [comment]
Gah, that didn't work. @iandunn what did I do wrong in 70b8baf2ed1a3b965aa163204df45bec8208ae1d? I went through the steps in #683.

**Comment by iandunn** [comment]
@obenland are you talking about how it didn't automatically close this issue when you pushed it to master? Everything else looks good to me at first glance. It was squashed to a single commit and kept Hugo as the author, but shows that you were the one who merged it.

I added a comment to #683 about why the PR wasn't automatically closed:

> When editing the final, squashed commit, you need to manually add Fixes {#NNN} to the commit message, because rebasing generates a new commit ID, so GitHub no longer knows that the commit is tied to the issue.

Sorry I forgot to mention that at first.

**Comment by hugobaeta** [comment]
This is still marked as open, but it seems like what I did is now in _s - but it doesn't show in my contributions to the project tho :(

Should I close this? I also have a button here to "Merge Pull Request"... What should I do?

**Comment by iandunn** [comment]
Yeah, it was merged in 70b8baf2ed1a3b965aa163204df45bec8208ae1d, but the PR wasn't automatically closed [because it was rebased without adding a `Fixes #{issue}` note in the commit message](https://github.com/Automattic/_s/pull/714#issuecomment-85326673).

You're still listed as the author of that commit, though, and I see it in [your contributions](https://github.com/Automattic/_s/commits?author=hugobaeta).

**Pull request closed without merging**
