### PR TITLE
Navigation - menu ancestor fix

### PR DESCRIPTION
**Pull request by roarytubbs**
Renamed
.current_page_ancestor > a
to
.current-page-ancestor > a,

### CODE REVIEW

**Comment by karmatosed** [comment]
Does this fix a particular ticket or issue? Would be great to see context here, thanks.

**Comment by philiparthurmoore** [comment]
@roarytubbs ^

**Comment by roarytubbs** [comment]
This was just a simple css fix. The current class was not named properly.

**Comment by gatespace** [comment]
Looking at the reference seems to correct the `current_page_ancestor`.
see:
https://developer.wordpress.org/reference/functions/wp_nav_menu/#backward-compatibility-with-wp_page_menu

Does this change is necessary?
What is WordPress version?

**Comment by bahiirwa** [comment]
Check #998 there is a similar issue

**Comment by davidakennedy** [comment]
Thanks for the contribution @roarytubbs! As far as I can tell, the current classes should cover all the needed situations. This was brought up in another issue as well. See: https://github.com/Automattic/_s/issues/1073#issuecomment-272638073

I'm going to close this out, but if I'm missing something, feel free to comment and I'll take a look.

**Pull request closed without merging**
