### PR TITLE
Removing unnecessary ampersands, fixes #791

### LINKED ISSUE #791: Unnecessary Sass ampersand for post navigation
I don't think that these ampersands are necessary for the post navigation. The post nav classes are appended to the parent class either way. Perhaps there's something I've overlooked though.

```
	& .nav-previous {
		float: left;
		width: 50%;
	}

	& .nav-next {
		float: right;
		text-align: right;
		width: 50%;
	}
```

https://github.com/Automattic/_s/blob/00e6610198a0fbed48c13765f6b532889e7a8db6/sass/navigation/_menus.scss#L87-L104

I'll be happy to submit a pull request that removes them if it's agreed they're superfluous.

### PR DESCRIPTION
**Pull request by jamigibbs**
Submitting this as described in #791

### CODE REVIEW

**Comment by philiparthurmoore** [comment]
@jamigibbs Can you [squash](https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) these two commits into one? Thanks!

**Comment by jamigibbs** [comment]
Sorry for the delay! Just getting to this now but not sure I squashed it correctly. Feel free to toss more links my way with tips if I should to try again. 📡

**Comment by obenland** [comment]
The goal would be to have it all in one commit. Maybe this helps? http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit/

**Comment by jamigibbs** [comment]
Thought I had. Thanks for the link though! I'll have to take a look at this more tomorrow.

**Comment by jamigibbs** [comment]
Apologies for the inconvenience here but I'm going to close this and resubmit on a clean commit.

**Comment by philiparthurmoore** [comment]
> Apologies for the inconvenience here but I'm going to close this and resubmit on a clean commit.

Can't count how many times I've done this. :smile: Thanks a ton for getting that new PR done. Cheers!

**Pull request closed without merging**
