### PR TITLE
Change links from http to https 

### PR DESCRIPTION
**Pull request by Umangvaghela**
update automatic link

### CODE REVIEW

**Comment by Umangvaghela** [comment]
Hello all

Any one can review this.

**Comment by grappler** [comment]
Related to https://github.com/Automattic/_s/pull/1172

Please change all of the URLs to HTTPS and not just one.

**Comment by Umangvaghela** [comment]
@grappler 

Thanks for the reply. I will change link as soon as possible.

**Comment by B-07** [comment]
This was already submitted #1172 which now has a refresh #1214

**Comment by grappler** [comment]
Closing as this is solved in #1214

**Pull request closed without merging**
