### PR TITLE
Add woocommerce to docs

### PR DESCRIPTION
**Pull request by bahiirwa**
#### Changes proposed in this Pull Request:
Add information to documentation that _s is Woocommerce ready with a starter boilerplate

#### Related issue(s):
PR #1244

### CODE REVIEW

**Comment by bahiirwa** [comment]
@crunnells here it is.

**Comment by bahiirwa** [comment]
I have done a rebase. Hope that refreshes things.

**Comment by grappler** [comment]
Strange that the other commit gets added like that. @bahiirwa Do you think you can squash your commits together?

**Comment by grappler** [comment]
@bahiirwa A little tip. If you create a separate branch for each pull requests then you can have multiple pull requests at one time instead of using the `master` branch.

**Pull request closed without merging**
