### PR TITLE
Update Normalize.css to v7.0.0

### PR DESCRIPTION
**Pull request by mtomas7**
I condensed similar styles as it was in previous _s version, but if needed I have normal version too. Personally, I prefer the normal version, as it makes much easier to compare with the original Normalize.css source.

### CODE REVIEW

**Comment by grappler** [comment]
@mtomas7 Thanks! Could you also update `sass/_normalize.scss` too?

Just for future reference the lone modification that was made before #895 has been fixed upstream so we should be ok in updating. necolas/normalize.css@fe56763

**Comment by mtomas7** [comment]
Sorry, but I only worked with LESS, perhaps someone else with more experience could do this?

**Comment by grappler** [comment]
From the looks of the `sass/_normalize.scss` file it is the same as the CSS so you don't need to know Sass to update it. In #1144 we were discussing about adding the version number to the Normalize header of the `style.css`.

**Comment by davidakennedy** [comment]
@mtomas7 Any interest in updating things here? Thank you!

**Comment by crunnells** [comment]
#1272 supercedes this PR, bringing us up to v8.0.0. Thanks for your initial work here @mtomas7!

**Pull request closed without merging**
