### PR TITLE
Remove blank line in head

### PR DESCRIPTION
**Pull request by B-07**
A blank line there looks so odd (to me and in general), looks much much better without the blank line 

#### Related issue(s):n/a

### CODE REVIEW

**Comment by jrfnl** [comment]
IMHO that blank line is there for a reason, i.e. to make it a *lot* easier to see that the code above it was HTML being added and the call below it is a function call.

**Comment by WaveRoutes** [comment]
I also thought so, but twentyfifteen, sixteen don't have that blank line

**Comment by jrfnl** [comment]
> but twentyfifteen, sixteen don't have that blank line

So what ? Learning from the twentysomethings for what they do right is a great thing, but let's not take over the things they do wrong.

**Comment by B-07** [comment]
By no means I meant that, If there's a reason that's fine.

**Comment by grappler** [comment]
I don't think we need to remove the the extra space.

**Comment by davidakennedy** [comment]
I don't think we need to remove the space here – it's not a big deal. 😄 

Thank you for the PR though, @B-07!

**Pull request closed without merging**
