### PR TITLE
`float` implies the use of the block layout

### PR DESCRIPTION
**Pull request by luizbills**
https://developer.mozilla.org/en/docs/Web/CSS/float

### CODE REVIEW

**Comment by karmatosed** [comment]
What are you trying to suggest by the link? I would love to grasp more what you are trying to fix over just linking to an article @luizbills.

**Comment by luizbills** [comment]
This:
```css
.main-navigation {
    display: block;
    float: left;
}
```

Is the same as:
```css
.main-navigation {
    float: left;
}
```

block is irrelevant there.

**Comment by philiparthurmoore** [comment]
Seems legit. 

image

**Comment by karmatosed** [comment]
Can either you @philiparthurmoore or @luizbills confirm what happens on different browsers and devices with this? I'm kind of thinking backwards with browser may not like dropping this.

**Comment by philiparthurmoore** [comment]
Agreed. It'd be smart to test this in important browsers even though in principle it seems legit.

**Comment by crunnells** [comment]
I'll take a look at some of the older browsers to see if there are any issues.

**Comment by crunnells** [comment]
Upon further consideration, this change will be moot with #1251 since it removes `float: left;` from the `.main-navigation` selector. If #1251 gets merged, we can close this issue.

**Comment by philiparthurmoore** [comment]
@crunnells Thanks for the heads up.

**Comment by Ismail-elkorchi** [comment]
Hi @gooklani 👋 ! Would you still be interested in updating this PR ? I tried to push some changes to this branch, but it seems that you don't [allow edits from maintainers](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

This change is always relevant as https://github.com/Automattic/_s/pull/1251 hasn't removed floats from `.alignleft` `.alignright` in [_alignments.scss](https://github.com/Automattic/_s/blob/master/sass/modules/_alignments.scss).

**Comment by Ismail-elkorchi** [comment]
Hi @luizbills 👋 ! Would you still be interested in updating this PR ? I tried to push some changes to this branch, but it seems that you don't [allow edits from maintainers](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

This change is always relevant as https://github.com/Automattic/_s/pull/1251 hasn't removed floats from `.alignleft` `.alignright` in [_alignments.scss](https://github.com/Automattic/_s/blob/master/sass/modules/_alignments.scss).

**Comment by luizbills** [comment]
@Ismail-elkorchi now maintainers can edit. Sorry for that

**Comment by Ismail-elkorchi** [comment]
No need to be sorry. Thanks @luizbills.

**Pull request merged**
