### PR TITLE
Using tabs instead of mixed tabs/spaces

### PR DESCRIPTION
**Pull request by gatespace**
Mixed usage of tabs/spaces for `/inc/jetpack.php` and `/sass/style.scss`.

### CODE REVIEW

**Comment by karmatosed** [comment]
This adds even more indenting, lets not do that for consistency. If we are going to change it should have the same spacing as other elements.

**Comment by gatespace** [comment]
Why?
WordPress Coding Standards (PHP Coding Standards and CSS Coding Standards) write '**Use real tabs** and **not spaces**'.

https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#indentation
https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/#structure

**Comment by sheabunge** [comment]
To me, this is clearly a positive change which makes _s more consistent both with itself and with the WordPress coding standards. Spaces should only be used for alignment, which isn't the case here.

**Comment by karmatosed** [comment]
The issue isn't if it's a positive change or not. The issue is you have added more than there was bringing it out of line with everything else.

**Comment by phoenixenero** [comment]
There is no "more indenting". If you're at the diffs in Github you'll see that the tabs are eight (8) whole spaces long. The actual tab character width used by most WordPress programmers is 4 spaces. There is no superfluous indentation, that's just Github's way of displaying tabs.

**Comment by philiparthurmoore** [comment]
@gatespace, can you show me what this looks like in you're code editor pre and post fix. I'm on mobile and GitHub diffs are hard to trust. 

Threads like this shouldn't be closed out so hastily.

**Comment by gatespace** [comment]
I changed from the four spaces in one tab.

**Comment by karmatosed** [comment]
@philiparthurmoore stating that someone hastily closed something is quite an assumption. I actually tested this. If we get a fix that works without causing more indent, I would of course have added it. I don't know if you did or not, however my approach is to applying each patch and testing as if you do that helps judge what the person closing may have seen.

**Comment by philiparthurmoore** [comment]
Yes it was a hasty close out. It's not a big deal either and not worthy of
discussion.

To the OP, what I meant was can you show me code editor screenshots? For
example, in Sublime I'm able to detect spaces versus tabs quite easily and
visually. Those diffs usually come out looking weird in GitHub even though
they are correct. Can you show me what you see so I understand why/how you
found these indentation issues? Thanks a ton.

**Comment by philiparthurmoore** [comment]
OP, I see your image now. That looks good. Let me open this up in Sublime later and see if I see the same problem. Thanks a ton.

**Comment by karmatosed** [comment]
I disagree and will stand by us closing things we open and see other issues in. Please do test this properly before merge.

**Comment by philiparthurmoore** [comment]
Not sure what that means but okay. We can agree to disagree. 

I've been managing pull requests on this since the project started. I don't need to be told to test a PR. Seems silly to me.

**Comment by karmatosed** [comment]
Not telling you to test @philiparthurmoore you are very much misunderstanding a lot in my comments, so please lets focus on this issue and get a correct PR.

**Comment by phoenixenero** [comment]
Copied and pasted the relevant lines from both branches:



The code is visually equivalent assuming a default tab `\\t` width of 4 spaces (which is what most WP programmers use.) I honestly have no idea what @karmatosed means by "more indent."

**Comment by philiparthurmoore** [comment]
This is exactly why I like screenshots with these PRs. Thanks. I'll get around to taking care of this tomorrow if it's not taken care of before then.

**Comment by phoenixenero** [comment]
Bumped. Is this gonna be merged anytime soon?

**Comment by philiparthurmoore** [comment]
"Soon" has a lot of meanings. My computer's bricked and in the shop. Back
to work next week for me. If no one has merged by then I'll do a close
review.

**Comment by philiparthurmoore** [comment]
Note: I live 8 hours away from an authorized Apple store in the mountainside of Vietnam with my wife and mother-in-law. Both of my Macs decided to punk me last week so I'll be fixing both and buying a third. Beautiful out here but when things break stuff comes to a stop for me. All this looks fine I just need my system back. 

image

Life.

image

Wife. Mother. And I'm not shown due to having emotional breakdowns about my computers dying simultaneously. 

image

**Comment by davidakennedy** [comment]
Let's stick to the business of making _s its best. We have a number of committers looking at issues weekly, and one of us will get to it as soon as possible.

**Comment by philiparthurmoore** [comment]
As I said I'll give it a look this weekend. I'm a committer. The PR is
solid. Just need to test it.

Nothing to worry about here.

**Comment by philiparthurmoore** [comment]
Done. For the curious, here was the before:




And here's the after:




@gatespace, thanks for your patience. This should have never taken so long to discuss or resolve; it's probably one of the most insignificant changes that turned into a longer discussion than it needed to be that I've ever merged. I really appreciate you waiting on me to dig into your PR and make screenshots so that in the future this makes sense for any newbies who don't understand why this was an issue.

And thanks for your good eyes. Great catch. And, thanks for your contributions to _s. 😄

**Comment by gatespace** [comment]
@philiparthurmoore, Do not worry.
Then if there is a similar pull request, I attach a screen shot. ;)

**Pull request merged**
