### PR TITLE
Fix translatability of comments title.

### PR DESCRIPTION
**Pull request by jrfnl**
As per the guidelines in https://codex.wordpress.org/I18n_for_WordPress_Developers#Plurals

> Note that some languages use the singular form for other numbers (e.g. 21, 31 and so on, much like '21st', '31st' in English). If you would like to special case the singular, check for it specifically

This fixes an error notice which WPCS will start throwing once the - soon to be released - 0.10.0 version has become stable.

### CODE REVIEW

**Comment by jrfnl** [comment]
All: the travis build of the `master` branch is currently failing as it is now tested against the 0.10.0 version of WPCS. This PR will fix that.

**Comment by karmatosed** [comment]
Can we get a refresh on this patch as it has conflicts?

**Comment by jrfnl** [comment]
Refreshed (.pot file)!
N.B. I added one extra commit to add the missing translators comments to the new strings.

**Comment by balcsida** [comment]
Merge maybe?

**Comment by davidakennedy** [comment]
Thanks for the work here @jrfnl!

**Pull request merged**
