### PR TITLE
Wrap theme functions inside function_exists() check

### PR DESCRIPTION
**Pull request by pattonwebz**
#### Changes proposed in this Pull Request:

This PR wraps theme functions inside of `function_exists()`.

NOTE: `/inc/woocommerse.php` functions are not currently wrapped.

#### Related issue(s): 
#1116

### CODE REVIEW

**Comment by pattonwebz** [comment]
@davidakennedy The woocommerse.php file in the theme uses a different format for the `if` statements wrapping the function check than what was already used throughout the rest of the theme. That file uses `if () {..}` style wrappers where as the rest of the theme uses `if () : endif;`.

Should I normalize all the calls to be the same syntax and if so which method would be preferable?

**Comment by samikeijonen** [comment]
I think current standard is to use `if () : endif;` in template files, and `if () {..}` in other files.

**Comment by grappler** [comment]
As I mentioned in the issue https://github.com/Automattic/_s/issues/1116#issuecomment-307690097 I don't agree with making all functions pluggable.

**Comment by pattonwebz** [comment]
@grappler so your preference is that only a small number (those which cannot be unhooked or support removed easily) should be overloadable?

I can do that if that's what is called for but you'll need to let me know what the list of functions to wrap are because people have different opinions on what is considered _easily removed_ lol

**Comment by grappler** [comment]
> so your preference is that only a small number (those which cannot be unhooked or support removed easily) should be overloadable?

Yes that would be my preference.

> I can do that if that's what is called for but you'll need to let me know what the list of functions to wrap are because people have different opinions on what is considered easily removed lol

The steps that are needed would be https://github.com/Automattic/_s/issues/1116#issuecomment-307952674

I am not sure how to come to a decision or who makes the final decision..

**Comment by philiparthurmoore** [comment]
Agree completely with @grappler's take on this.

**Comment by Ismail-elkorchi** [comment]
Hi @pattonwebz 👋 ! Would you be still interested in updating this PR ? If not, no worries, I can pick up the work where you left off if you want, just let me know.

**Comment by kangabell** [comment]
I'd find this change helpful!
@Ismail-elkorchi I see that @pattonwebz has not responded – are you still interested in picking this up?

**Comment by Ismail-elkorchi** [comment]
@kangabell of course. I'll look it over today or tomorrow at the latest. thanks for the reminder :)

**Comment by Ismail-elkorchi** [comment]
I have created a new PR https://github.com/Automattic/_s/pull/1480 to adress this issue based on https://github.com/Automattic/_s/issues/1116#issuecomment-307952674.

**Pull request closed without merging**
