### PR TITLE
Add bang to scss stylesheet header to prevent it being removed. Fix #715

### LINKED ISSUE #715: When sass is compiled with compressed output mode, stylesheet header is lost
Need to add a bang, as described in the [SASS docs](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#comments), to the comment.

### PR DESCRIPTION
**Pull request by acusti**

### CODE REVIEW

**Comment by obenland** [comment]
Opinions?

**Comment by ScottSmith95** [comment]
I've had to do this, especially to prevent my build processes from removing the theme info and breaking the theme. I had concerns about this, but this seems to be a very standardised way of preventing comment removal and WordPress has no problem with it.

**Comment by glueckpress** [comment]
The related issue #715 was closed as wontfix-for-now by @davidakennedy. Is it being reopened? Otherwise I don’t see the point of this PR.

**Comment by acusti** [comment]
I didn’t even realize the PR was still open. Sorry about that!

**Pull request closed without merging**
