### PR TITLE
Remove unnecessary !

### PR DESCRIPTION
**Pull request by B-07**
#### Related issue(s):

### CODE REVIEW

**Comment by davidakennedy** [comment]
@B-07 Thanks for the PR. Great catch!

One thing I'll mention: please put an explanation of your changes in the PR. No matter how simple. It's tedious sometimes, yes. However, this is a good habit to learn as a developer because:

- You get better at explaining things.
- You make a project maintainer's life easier.
- It's helpful when digging back through history, wondering why a certain change was made.
- We kindly ask you to do it by providing a PR template. 😄 

Thanks again for your contributions!

**Comment by B-07** [comment]
@davidakennedy Thank for the suggestions, I'll follow those from now on for sure.

**Comment by grappler** [comment]
@davidakennedy I don't think this was supposed to be removed. We added it deliberately in https://github.com/Automattic/_s/commit/e9c7d73be804365e44934f2b01b70e0110bcef13 in #770

**Comment by davidakennedy** [comment]
Ah, I looked and missed that @grappler! Thanks for catching it. Will revert.

**Pull request merged**
