### PR TITLE
Reduce one step to search replace theme name.

### PR DESCRIPTION
**Pull request by rahulprajapati-rtcamp**
Hello,
Here I have tried to reduce one step for search and replace theme name using define( 'THEME_NAME', '_s' ).

### CODE REVIEW

**Comment by emiluzelac** [comment]
Hi,

You can go to http://underscores.me enter the text domain only once and
generate in seconds. Patch for this is neither recommended or needed :)

**Comment by rahulprajapati-rtcamp** [comment]
Yes I know that but as https://github.com/automattic/_s repo has search and replace steps for theme rename. I just tried to reduce that steps.
Thank You . :)

**Comment by obenland** [comment]
It's a neat idea, but you can't use constants as textdomains with gettext.
We already have a search/replace engine in place, so there is no need to reduce the work load. That would actually be more work. :)

**Comment by emiluzelac** [comment]
Not only that, all textdomain must be hardcoded string too. Also see:
https://markjaquith.wordpress.com/2011/10/06/translating-wordpress-plugins-and-themes-dont-get-clever/

**Pull request closed without merging**
