### PR TITLE
Remove period from file header

### PR DESCRIPTION
**Pull request by B-07**
According to [WordPress PHP Documentation Standards ](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#6-file-headers) there shouldn't be period after the file header

Fixes issue #1030

### CODE REVIEW

**Comment by B-07** [comment]
@grappler mate can you please help me understand why it failed checking

**Comment by josephfusco** [comment]
Travis failure is unrelated to this PR. Fix from @jrfnl is in #1012 which is waiting to be merged.

**Comment by B-07** [comment]
@josephfusco so you're saying all changes I did is ready to be approved?

**Comment by josephfusco** [comment]
@B-07 correct

**Comment by corvannoorloos** [comment]
@B-07 @karmatosed I'm not entirely sure why the "Theme Name" was changed to "_sss"?

**Comment by karmatosed** [comment]
Good find @corvannoorloos - I've resolved it now.

**Pull request merged**
