### PR TITLE
Split _s_posted_on into two functions

### PR DESCRIPTION
**Pull request by Ismail-elkorchi**
#### Changes proposed in this Pull Request:
Split `_s_posted_on()` into two functions : `_s_posted_on()` and `_s_posted_by()`

#### Related issue(s): https://github.com/Automattic/_s/issues/1213

### CODE REVIEW

**Comment by Ismail-elkorchi** [comment]
Thank you @grappler for the review. I just updated the PR.

**Comment by dshanske** [comment]
Any movement on this one? It looks like the changes were made.

**Comment by laurelfulford** [comment]
Thanks @Ismail-elkorchi!

**Comment by Ismail-elkorchi** [comment]
My pleasure @laurelfulford !

**Pull request merged**
