### PR TITLE
Format SCSS

### PR DESCRIPTION
**Pull request by m-e-h**
#### Changes proposed in this Pull Request:
Lint and properly format SCSS so it'll produce a properly formatted `style.css`

#### Related issue(s):
https://github.com/Automattic/_s/issues/1149
https://github.com/Automattic/_s/pull/1159
https://github.com/Automattic/_s/pull/932
#893

### CODE REVIEW

**Comment by m-e-h** [comment]
Oops. Looks like I need to squash a few commits here. Reckon I should add the compiled `style.css` too...

**Comment by m-e-h** [comment]
The updated `style.css` has a couple minor quirks  due to `node-sass` and/or WP CSS standards. 
1. empty selector blocks for the menu section only appear in the SASS files.
2. single line comments on the same line as a parameter have been changed from `/* */` to `//`, so they only show in the SASS files, as well. This is because during compilation the `/* */` was being moved to it's own line.

If automating the `style.css` generation through SASS compilation the goal, I don't see many ways around making some adjustments like this. 

I did still have to make one manual fix to the `style.css`.
I think it was `node-sass` that didn't seem to like this piece of code.
```
.comment-navigation,
.posts-navigation,
.post-navigation {

	.site-main & {
		margin: 0 0 1.5em;
		overflow: hidden;
	}
}
```
It produced this in the CSS
```
.site-main .comment-navigation,
.site-main
.posts-navigation,
.site-main 
.post-navigation {
	margin: 0 0 1.5em;
	overflow: hidden;
}
```
The SCSS will probably need adjusted here but I thought that could be done after this commit?
Please let me know any thoughts on these or anything else that doesn't look right.

**Comment by m-e-h** [comment]
Just noticed this has some overlap with this https://github.com/Automattic/_s/pull/1153 and this https://github.com/Automattic/_s/pull/1170

**Comment by grappler** [comment]
Thank you for the PR.

As #1149 has started to question the need for Sass we will need to wait to merge this till we have a resolution.

As we are planning to update Normalize in #1155 the pull request will need to be refresh afterwards.

**Comment by Ismail-elkorchi** [comment]
The formatting issues of SASS and CSS were resolved in https://github.com/Automattic/_s/pull/1391

**Pull request closed without merging**
